### ISSUE TITLE
Push recent releases to pypi

### ISSUE THREAD

**Issue by MacFan4000** [sopel-irc/sopel-weather#25]
At least the last two releases have not been released on PyPi. It’s because they haven’t been tagged on GitHub, and Travis CI no longer seems to run. It may be worth moving to a new CI such as GitHub actions. It can be setup the way Travis was with releases only being pushed if they’ve been tagged on GitHub. I created a workflow that runs the same checks - https://github.com/MacFan4000/sopel-weather/blob/master/.github/workflows/ci.yml

**Comment by RustyBower** [comment]
yep, it's been on my list for a few days. thanks for the github workflow, should make migration easier

**Comment by MacFan4000** [comment]
I have created a Pull Request that should completely do the migration (#26).

**Comment by RustyBower** [comment]
This is fixed in https://github.com/sopel-irc/sopel-weather/commit/8a82b45196776925ac9a775cf27dc0f5a1187e4c
