### ISSUE TITLE
Sunrise and sunset are displayed in timestamp format

### ISSUE THREAD

**Issue by sukiletxe** [sopel-irc/sopel-weather#30]
I'm using openweathermap as my weather provider, and the sunrise and sunset information are displayed in timestamp format (not sure if seconds or milliseconds). I don't know if the proper way to fix this would be to do a strptime / strftime round-tripor if there's a better way.

**Comment by RustyBower** [comment]
Can you copy paste the command and output you're getting? Also what your
weather section looks like in settings (please comment out your API key)

**Comment by sukiletxe** [comment]
```
.w howston
Sarnia, Ontario, CA: 19°C (67°F), Clouds, Humidity: 74%, Sunrise: 1623664189 Sunset: 1623719401, Gentle breeze 4.9m/s (↙)

geocoords_provider = locationiq
weather_provider = openweathermap
sunrise_sunset = true
nick_lookup = true
```

**Comment by dgw** [comment]
OWM docs for the "onecall" API this plugin uses [say](https://openweathermap.org/api/one-call-api#hist_parameter) that sunrise/sunset are Unix timestamps in UTC. I can't access the Dark Sky API documentation for comparison, as I don't have an account.

Regardless of Dark Sky, the obvious solution for OWM is converting the value to a `datetime` using [`datetime.fromtimestamp()`](https://docs.python.org/3/library/datetime.html#datetime.datetime.fromtimestamp) and formatting it with [`sopel.tools.time.format_time()`](https://sopel.chat/docs/api.html#sopel.tools.time.format_time).

If it's supposed to be the weather provider's job to format the value into a human-friendly string, then the place to do that is here:

https://github.com/sopel-irc/sopel-weather/blob/3ae16772e712c48c6b6db4b936359fcb93dea888/sopel_modules/weather/providers/weather/openweathermap.py#L64-L66

**Comment by sukiletxe** [comment]
Seems both use timestamps in seconds. Should I create only two functions in `weather.py` (just like `get_temp`, for example, one for sunrise and another one for sunset), or should I split the logic just in case incompatible providers are added?

**Comment by sukiletxe** [comment]
Woops, didn't think of that ¬¬ . OK, will do.
