### ISSUE TITLE
API Change

### ISSUE THREAD

**Issue by RustyBower** [sopel-irc/sopel-weather#38]
Hello,
 
We’re pushing a few changes to ensure continued service, higher availability, and lower latencies for our APIs.
 
What’s changing?
 
On 1st June 2022 at 00:00 UTC, we’re going to deprecate some endpoints used to reach our Geocoding, Routing & Timezones APIs. These include older & root domain endpoints such as [us1.locationiq.org/v1](http://us1.locationiq.org/v1), [eu1.locationiq.org/v1](http://eu1.locationiq.org/v1), [locationiq.org/v1](http://locationiq.org/v1), and [locationiq.com/v1](http://locationiq.com/v1).
 
 
Starting 1st June, our Geocoding, Routing & Timezone APIs will only respond to requests sent to these two endpoints - https://us1.locationiq.com/v1, and https://eu1.locationiq.com/v1. 
 
There are no changes to other APIs:
Autocomplete API requests - [api.locationiq.com/v1](http://api.locationiq.com/v1)
Static Maps - [maps.locationiq.com/v3](http://maps.locationiq.com/v3)
Map Tiles - [tiles.locationiq.com/v3](http://tiles.locationiq.com/v3)
 
What you need to do
 
If you’re using one of our new endpoints - you’re good! If you’re using any of the older endpoints, please update your request URLs to the above-mentioned endpoints. 
 
Please check out our [documentation page](http://r.ml.locationiq.com/mk/cl/f/5cbX9ySw2B3wGtn7a3ZQ4DwD0WIMeBIwQLeXAQbONdpDpFRRqFOF17DkU7YpTM7fQqlr_UH4kS0U4v6XktRWQC36jckJij1zDompg3xBsQPu099dSVxr2ZpuFUyqKTM0WyAc5svh94rOx1cTylpgVfDTqGIU83xhXpAYpA5V_9J7ww_rwYqImcxNcu24JY9j0Q) for more information about our APIs. Just hit reply if you have any questions, we’d be happy to help.

**Comment by dgw** [comment]
Based on the options selectable from `GEOCOORDS_PROVIDERS`, this should be fine.

https://github.com/sopel-irc/sopel-weather/blob/b17bacf982625daa81e99af3d675d593f16e45f5/sopel_modules/weather/weather.py#L28-L33
